blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/matheuschignolli/foldnize/discussions
    about: |
      For open-ended questions, ideas you haven't fleshed out yet, or
      "is this a bug?" doubts, please start a discussion instead of opening
      an issue.
